# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9
language: swift

before_install:
  - brew update
  - brew upgrade carthage
  - brew outdated xctool || brew upgrade xctool
  - carthage update

script:
  - xcodebuild -project "Sheeeeeeeeet.xcodeproj" -scheme "SheeeeeeeeetExample" -sdk "iphonesimulator" | xcpretty -c
  - fastlane test
